# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "i2c-dev" ];
  boot.extraModulePackages = [ ];
  services.xserver.enable = true;
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs;[
      nvidia-vaapi-driver
      libva
    ];
  };
  services.udev.extraRules = ''
    KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"
  '';
  users.groups.i2c = { };
  boot.kernelParams = [ "nvidia.NVreg_PreserveVideoMemoryAllocations=1" ];
  hardware.nvidia = {
    open = true;
    powerManagement.enable = true;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/85a19bfa-f3aa-46bf-9c2b-dfcc83c70fca";
      fsType = "ext4";
    };
  fileSystems."/disk/Windows" =
    {
      device = "/dev/disk/by-uuid/5CD21C27D21C07C2";
      fsType = "ntfs";
    };
  fileSystems."/disk/Data" =
    {
      device = "/dev/disk/by-uuid/EBC220848C1B7A00";
      fsType = "ntfs";
    };
  fileSystems."/efi" =
    {
      device = "/dev/disk/by-uuid/F797-1796";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
