# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      vpl-gpu-rt
      intel-media-driver
      libvdpau-va-gl
    ];
  };
  environment.sessionVariables = {LIBVA_DRIVER_NAME = "iHD";};
  boot.kernelParams = ["i915.force_probe=4fa0"];
  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["i915"];
  services.udev.extraRules = ''
    KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"
  '';
  users.groups.i2c = {};
  boot.kernelModules = ["kvm-amd" "i2c-dev"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8482001d-e49f-44cf-b587-6d4d2db65fc3";
    fsType = "btrfs";
    options = ["subvol=fsroot" "compress=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/8482001d-e49f-44cf-b587-6d4d2db65fc3";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8482001d-e49f-44cf-b587-6d4d2db65fc3";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime" "compress=zstd"];
  };
  fileSystems."/disk/data" = {
    device = "/dev/disk/by-uuid/5C3616BF02322C8B";
    fsType = "ntfs";
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/8E98-8287";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  # swapDevices = [{
  #   device = "/var/lib/swapfile";
  #   size = 8 * 1024;
  # }];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
