clash_url: ENC[AES256_GCM,data:dwp1hfnnEgiQMoOSbx14XdAfgAUCMiTTps9kqtIPztAp7cqry6iRYe2f6+Um7GxdAfzvAFQTyh7m6uUol11HVKbaxA==,iv:iRP1VjPbgy1ioNS4WMZq1ImHBcil7FOROrzmxmGAjFI=,tag:KSmGVUSywr94InoU2t3m6Q==,type:str]
github_token: ENC[AES256_GCM,data:RgfgkD9X0ra1oP4TNJkRLEZ69OwnIqsbf83+YDh/kCFOpu4Gep3LOg==,iv:xGlFCmhtkxOzxvTHdV9X6cB5C3IwrWTCG78JuU8uhbk=,tag:zf4TUfUkR+mEDbfdRzEXPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age102h2qxkhas3lkxm7q2z8pq2jtgl2vmn9tt9pkmfdauhhykd7xypqj7mgdj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwajRTQVZVRUdDaTVpQStM
            QzZ4MFpqSklaVFhuN2tNazJub2YzdGVFS3lNCnQxNFFGSjRWQUtNeEVFUkZUS2FZ
            dWdDU3JlcExOazhIVk9rY3o3QlFjVlUKLS0tIFhPZEtTVUwrbENKSkRlWmI2ZzFj
            VXBpU2I5VlgyNld3ODczdHBHYktLWUkKBNhy87592Or2piIz5g4QYD02NLrrrKq4
            MwGVGB9mNAo4E7RUsd+y4OBx0QUgaxifaww8tXPdZB4ykO1dplKNhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T13:17:23Z"
    mac: ENC[AES256_GCM,data:uJLtFzlNI/SJIRDcwf40nLzgelQhNy40bNm8B4+qogm0mvEfgIldHq5pSHs2r2SN3wWsrUeBrcSKIqKegkxAxit0Fa+kfrHKmxAKK+pQgxfa6Oumnk3OK2SOYwCQ7zE0XTrh+vD2xhUWoZgXLpsXFi2Ode6kJNmRlZw/5t6wYh0=,iv:p3DTzHWIzv6eisdw9HaPB34k0igFVyyw/NgyiknEiBc=,tag:MQmfGKqoJ0iFsV1MOaRpRA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
