password:
    root: ENC[AES256_GCM,data:4zEYTBQHZXpmSXBY1PsEfKPBZRVrfIgIu/tz2m6quufi+emM74Az6+MXwvGOYwZhkH7vejn6Mr7c3UWsvNl2nt8b6c3lpX1UM0mqcm/+UR01onIOS7plTYPZ+Tly2sffzrzbHMJ7wrINmA==,iv:izYvfgfAREKmY+vg01x3R0Y4b6NAIpr8nrpdK3Vyx7s=,tag:5TC/WW5THy11ESQ7o7d1Tg==,type:str]
    humxc: ENC[AES256_GCM,data:7jmLe8Bu2l+lEITH4Bah59zM9yV2AqeoXuSBxldpd4OIha+k7/rJPkJPnjJX2SaXKOdrWHxzSK/HHWbTP5PbjZZdUgGd02Tz2eY3WTbflv7g0rM5Zs5AGzjTIE+EAZJqpwudExoMJRJN8A==,iv:YffZXJPZTjhjJ6osiWyoAvpI+H6WBmSSPOB8eiRTnPc=,tag:lMqITEUi0O1dpymvRdeujQ==,type:str]
clash_url: ENC[AES256_GCM,data:3qenbEHATJEt1XDI5kRx8tkFg9Yl/QRQzRMimIIzL8Xv2Z0zelpU1djT3fCbTdJWRCqU89a7LS3q96gFIS5GNQAGjQ==,iv:sMUb8DXOUO1xPZpXlg+Jflgl1/doqOLTGCQ+QST9suE=,tag:kE4HPcoRfjEcGTf7QRS6qg==,type:str]
github_token: ENC[AES256_GCM,data:Oj94ROHjOplpxHkDH9Cvbxli7uuk0vkAEe82r3ft9u6kbgD0//+trA==,iv:D6mXslCplwPtvcqv97ZyGTzm3qgYaKJ15cUjGVFrKgQ=,tag:dwNty1wJ2uqBsVtj7C5lOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age102h2qxkhas3lkxm7q2z8pq2jtgl2vmn9tt9pkmfdauhhykd7xypqj7mgdj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERm91eHc5UXh4N1FrMGp6
            WDZHdmtiUytDRzRUektab01yZTJuR2ZSQ2lZCjhVVHg2U3VZeFVUVmR4NEFMaGZV
            YUVLKy9xdzd6M01EVTBuTXhzZTE1V3cKLS0tIGpPVTd3UWdLdlN4Ym1CV1ZjWkVn
            c1BRSXE4QnVqU0JRNGF3WHFJeEZLM1UKM9PFly+fPjdkb02drSgg891ZBvCUQhDh
            ViWLLg2cOGs/ClUJL5pC1KRYPrIW2RKSOWWkF86GPKwKZKC216fh3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yjqvf59yfrdg65jackdkks0lh0t4y9nl5aczt4h0m7gj4vx6gxqwdv5ww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa1Uzcmh3b0lHQkpGSEhD
            YkFGOWtjdTRjUk1GTnora0JCbVo5UnVUTlE0CjRDYlEva0tnaElldkVjdTlkVVBK
            WUphbmplQjdGMU0zMVJMK2lvakw5ancKLS0tIG1WT0xmSTdkR1Y2QjFSc2o5Ykd2
            b29UbzNONmloc0p1NnJVRFNMWUdnY2MKBIMwYLYyl6L6xABtqIVPWRuFOZje2Vg8
            vjCAiTMX+4gtiCIBAb2qWs5TlO1A7LisPFoIgAXEi/9JzrlqQXbWyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T04:14:56Z"
    mac: ENC[AES256_GCM,data:0+MWi+LlxVwJE8mnKXbdt1hMCvmGA0ystb5GbL2LgzhBB8G+P5uErlAhDVv+6axr8vjT+17VUFYnok+pIByr8bkX1/0ZVHTJ1XQQ3V+MQcSo5XjfUPCLxTkBTgf6FYAKt/9PAnlKWI3S3OxdjIHJfdGTc3EFyxHtGL0hXJ2483A=,iv:QcKEEY3b15oHKcoygQ7fMlv1Dc9bAOR3wGuglEmHUvM=,tag:pKwnlOIvE1nxDs2o2RKk8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
